debug: true

server:
  compression:
    enabled: true
    min-response-size: 4096
    mime-types:
      - application/javascript
      - application/json

spring:
  mvc:
    format:
      date: iso
      date-time: iso
      time: iso
  mail:
    host: smtp.x.com
    port: 25
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/pepe
    username: root
    password: root
    hikari:
      schema: x
      maximumPoolSize: 10
      connectionTimeout: 30000
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  flyway:
    enabled: false
    locations: classpath:/db/migration
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://x/v2.0/
          jwk-set-uri: https://x/discovery/v2.0/keys?p=b2c_1_login

logging:
  level:
    org.hibernate:
      SQL: INFO
      type.descriptor.sql.BasicBinder: TRACE

app:
  url: http://localhost:8080
  language:
    default: es
  mail:
    from: poc@clavei.com
  version: 1.0